#!/usr/bin/env bash


# modify this to desired location
journal_file_location=~/personal/private_journal/journal.md

entry=$(cat << EOF
\n# $(date +%m-%d-%y)          
\n## CBT                       
\n### Biased Thought           
\n#### Cognitive Distortions   
\n##### mental filter          
\n##### overgeneralization     
\n##### catastrophizing        
\n##### minimizing the positive
\n### Reworded Thought         
\n## 3 things I\'m Grateful for 
\n## issues
\n### issue
\n- worry:
\n- desired outcome:
\n- next step:
\n## procrastination
\n### avoided
\n### succumbed
\n## Goals                     
\n- meditate                   
\n## Schedule                  
\n### Goal Breakdown           
\n### Frustration Log          
\n### Distraction Log          
\n## Batched Internet Searches 
\n##75 hard
\n[] 5 hours of focused work 
\n[] one of: 30 min cardio, heavy weights, pushups/pullups/situps 
\n[] 1/2 gallon of water
\n[] in bed by 10pm
\n[] < 20g sugar
\n## Recap\n                   

EOF
)

# is there daily entry?
if test -f $journal_file_location
then
  todays_date_count=$(grep -c "# $(date +%m-%d-%y)" $journal_file_location) 
else
  todays_date_count=0
fi

# add daily entry if not present
if [ "$todays_date_count" -eq 0 ]
then
  printf "$entry" >> $journal_file_location
fi


# update to nano or code, for example
editor=nvim
# open journal wherever you are. Neat right?
$editor $journal_file_location
