#!/usr/bin/env bash


# whatever echo ~ evaluates to on your machine
journal_file_location=~/work/journal/journal.md

# update to nano, for example
editor=nvim

if test -f $journal_file_location
then
  todays_date_count=$(grep -c "# $(date +%m-%d-%y)" $journal_file_location) 
else
  # trigger the echo block if file doesn't exist
  todays_date_count=0
fi

if [ "$todays_date_count" -eq 0 ]
then
  # journal template
  echo -e "\n# $(date +%m-%d-%y)" >> $journal_file_location
  echo -e "\n## _blank_" >> $journal_file_location
  echo -e "\n## 3 things I'm Grateful for" >> $journal_file_location
  echo -e "\n## Goals" >> $journal_file_location
  echo -e "\n- meditate" >> $journal_file_location
  echo -e "\n## Schedule" >> $journal_file_location
  echo -e "\n## Batched Internet Searches" >> $journal_file_location
  echo -e "\n## Recap\n" >> $journal_file_location
fi


# open journal wherever you are. Neat right?
$editor $journal_file_location




